//
//  TaskMasterApp.swift
//  TaskMaster
//
//  Generated by Kalki AI Design System
//  2025-11-06
//

import SwiftUI

@main
struct TaskMasterApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
