
// design_20251106_153529 - Generated by Kalki Design Engine
// Generated: 2025-11-06T15:35:29.348400
// Design Type: robotics


// Preview helpers (only rendered in OpenSCAD preview mode)
module preview_axes(axis_len=120) {
    color([1, 0, 0, 0.3]) cube([axis_len, 2, 2], center=true); // X-axis
    color([0, 1, 0, 0.3]) cube([2, axis_len, 2], center=true); // Y-axis
    color([0, 0, 1, 0.3]) cube([2, 2, axis_len], center=true); // Z-axis
}

module preview_origin_marker(size=4) {
    color([1, 0.5, 0, 0.5]) sphere(r=size);
}

// Mechanical component libraries
module servo_motor(length=60, diameter=40, shaft_diameter=6, shaft_length=20) {
    // Motor body
    color([0.3, 0.3, 0.3]) cylinder(h=length, d=diameter, center=true);
    // Mounting flanges
    color([0.4, 0.4, 0.4]) {
        translate([0, 0, length/2 + 2]) cylinder(h=4, d=diameter + 10, center=true);
        translate([0, 0, -length/2 - 2]) cylinder(h=4, d=diameter + 10, center=true);
    }
    // Shaft
    color([0.8, 0.8, 0.8]) translate([0, 0, length/2 + shaft_length/2]) cylinder(h=shaft_length, d=shaft_diameter, center=true);
    // Mounting holes
    for (angle = [0, 90, 180, 270]) {
        rotate([0, 0, angle]) translate([diameter/2 + 5, 0, 0]) cylinder(h=length + 10, d=3, center=true);
    }
}

module bearing(outer_diameter=30, inner_diameter=10, thickness=8) {
    // Outer race
    color([0.6, 0.6, 0.6]) difference() {
        cylinder(h=thickness, d=outer_diameter, center=true);
        cylinder(h=thickness + 2, d=inner_diameter, center=true);
    }
    // Inner race
    color([0.7, 0.7, 0.7]) cylinder(h=thickness - 2, d=inner_diameter + 4, center=true);
    // Balls (simplified)
    color([0.9, 0.9, 0.9]) for (angle = [0:45:315]) {
        rotate([0, 0, angle]) translate([(outer_diameter + inner_diameter)/4, 0, 0]) sphere(r=2);
    }
}

module gear(radius=25, thickness=10, teeth=20) {
    // Gear body
    color([0.4, 0.4, 0.4]) cylinder(h=thickness, d=radius*2, center=true);
    // Teeth (simplified)
    color([0.3, 0.3, 0.3]) for (angle = [0:360/teeth:359]) {
        rotate([0, 0, angle]) translate([radius - 2, 0, 0]) cube([4, 3, thickness], center=true);
    }
    // Center hole
    color([0.2, 0.2, 0.2]) cylinder(h=thickness + 2, d=8, center=true);
}

module harmonic_drive(cup_diameter=60, flex_spline_diameter=50, thickness=15) {
    // Wave generator (simplified)
    color([0.5, 0.5, 0.5]) cylinder(h=thickness, d=cup_diameter * 0.7, center=true);
    // Flex spline
    color([0.6, 0.6, 0.6]) cylinder(h=thickness - 2, d=flex_spline_diameter, center=true);
    // Circular spline
    color([0.4, 0.4, 0.4]) difference() {
        cylinder(h=thickness - 4, d=cup_diameter, center=true);
        cylinder(h=thickness, d=flex_spline_diameter + 5, center=true);
    }
}

module robotic_link(length=200, diameter=40, wall_thickness=3) {
    // Hollow cylindrical link
    color([0.8, 0.8, 0.9]) difference() {
        cylinder(h=length, d=diameter, center=true);
        cylinder(h=length + 2, d=diameter - wall_thickness*2, center=true);
    }
    // End flanges
    color([0.7, 0.7, 0.8]) {
        translate([0, 0, length/2]) cylinder(h=6, d=diameter + 10, center=true);
        translate([0, 0, -length/2]) cylinder(h=6, d=diameter + 10, center=true);
    }
    // Mounting holes
    for (z_pos = [-length/3, 0, length/3]) {
        translate([0, 0, z_pos]) for (angle = [0, 90, 180, 270]) {
            rotate([0, 0, angle]) translate([diameter/2 + 5, 0, 0]) cylinder(h=8, d=4, center=true);
        }
    }
}

module end_effector(gripper_width=80, gripper_length=60, finger_length=40) {
    // Base
    color([0.3, 0.3, 0.3]) cube([gripper_width, gripper_length, 20], center=true);
    // Fingers
    color([0.5, 0.5, 0.5]) {
        translate([-gripper_width/4, gripper_length/2 + finger_length/2, 10]) cube([8, finger_length, 4], center=true);
        translate([gripper_width/4, gripper_length/2 + finger_length/2, 10]) cube([8, finger_length, 4], center=true);
    }
    // Actuator
    translate([0, -gripper_length/4, 15]) servo_motor(30, 25, 4, 10);
}

// Component 1: chassis
module component_0() {
    // Type: Provides chassis functionality
    cube([1.0, 1.0, 1.0], center=true);
}

// Component 2: actuators
module component_1() {
    // Type: Provides actuators functionality
    cube([1.0, 1.0, 1.0], center=true);
}

// Component 3: sensors
module component_2() {
    // Type: Provides sensors functionality
    cube([1.0, 1.0, 1.0], center=true);
}

// Component 4: controller
module component_3() {
    // Type: Provides controller functionality
    cube([1.0, 1.0, 1.0], center=true);
}

// Component 5: power
module component_4() {
    // Type: Provides power functionality
    cube([1.0, 1.0, 1.0], center=true);
}

// Assembly
translate([-120.00, -60.00, 0]) component_0();
translate([0.00, -60.00, 0]) component_1();
translate([120.00, -60.00, 0]) component_2();
translate([-120.00, 60.00, 0]) component_3();
translate([0.00, 60.00, 0]) component_4();


if ($preview) {
    preview_axes(axis_len=360.00);
    preview_origin_marker(size=6);
}
