
// Robotic Arm Assembly - Generated by Kalki Design Engine
// Generated: 2025-11-05T19:09:18.827052
// Design Type: robotic


// Preview helpers (only rendered in OpenSCAD preview mode)
module preview_axes(axis_len=120) {
    color([1, 0, 0, 0.3]) cube([axis_len, 2, 2], center=true); // X-axis
    color([0, 1, 0, 0.3]) cube([2, axis_len, 2], center=true); // Y-axis
    color([0, 0, 1, 0.3]) cube([2, 2, axis_len], center=true); // Z-axis
}

module preview_origin_marker(size=4) {
    color([1, 0.5, 0, 0.5]) sphere(r=size);
}

// Mechanical component libraries
module servo_motor(length=60, diameter=40, shaft_diameter=6, shaft_length=20) {
    // Motor body
    color([0.3, 0.3, 0.3]) cylinder(h=length, d=diameter, center=true);
    // Mounting flanges
    color([0.4, 0.4, 0.4]) {
        translate([0, 0, length/2 + 2]) cylinder(h=4, d=diameter + 10, center=true);
        translate([0, 0, -length/2 - 2]) cylinder(h=4, d=diameter + 10, center=true);
    }
    // Shaft
    color([0.8, 0.8, 0.8]) translate([0, 0, length/2 + shaft_length/2]) cylinder(h=shaft_length, d=shaft_diameter, center=true);
    // Mounting holes
    for (angle = [0, 90, 180, 270]) {
        rotate([0, 0, angle]) translate([diameter/2 + 5, 0, 0]) cylinder(h=length + 10, d=3, center=true);
    }
}

module bearing(outer_diameter=30, inner_diameter=10, thickness=8) {
    // Outer race
    color([0.6, 0.6, 0.6]) difference() {
        cylinder(h=thickness, d=outer_diameter, center=true);
        cylinder(h=thickness + 2, d=inner_diameter, center=true);
    }
    // Inner race
    color([0.7, 0.7, 0.7]) cylinder(h=thickness - 2, d=inner_diameter + 4, center=true);
    // Balls (simplified)
    color([0.9, 0.9, 0.9]) for (angle = [0:45:315]) {
        rotate([0, 0, angle]) translate([(outer_diameter + inner_diameter)/4, 0, 0]) sphere(r=2);
    }
}

module gear(radius=25, thickness=10, teeth=20) {
    // Gear body
    color([0.4, 0.4, 0.4]) cylinder(h=thickness, d=radius*2, center=true);
    // Teeth (simplified)
    color([0.3, 0.3, 0.3]) for (angle = [0:360/teeth:359]) {
        rotate([0, 0, angle]) translate([radius - 2, 0, 0]) cube([4, 3, thickness], center=true);
    }
    // Center hole
    color([0.2, 0.2, 0.2]) cylinder(h=thickness + 2, d=8, center=true);
}

module harmonic_drive(cup_diameter=60, flex_spline_diameter=50, thickness=15) {
    // Wave generator (simplified)
    color([0.5, 0.5, 0.5]) cylinder(h=thickness, d=cup_diameter * 0.7, center=true);
    // Flex spline
    color([0.6, 0.6, 0.6]) cylinder(h=thickness - 2, d=flex_spline_diameter, center=true);
    // Circular spline
    color([0.4, 0.4, 0.4]) difference() {
        cylinder(h=thickness - 4, d=cup_diameter, center=true);
        cylinder(h=thickness, d=flex_spline_diameter + 5, center=true);
    }
}

module robotic_link(length=200, diameter=40, wall_thickness=3) {
    // Hollow cylindrical link
    color([0.8, 0.8, 0.9]) difference() {
        cylinder(h=length, d=diameter, center=true);
        cylinder(h=length + 2, d=diameter - wall_thickness*2, center=true);
    }
    // End flanges
    color([0.7, 0.7, 0.8]) {
        translate([0, 0, length/2]) cylinder(h=6, d=diameter + 10, center=true);
        translate([0, 0, -length/2]) cylinder(h=6, d=diameter + 10, center=true);
    }
    // Mounting holes
    for (z_pos = [-length/3, 0, length/3]) {
        translate([0, 0, z_pos]) for (angle = [0, 90, 180, 270]) {
            rotate([0, 0, angle]) translate([diameter/2 + 5, 0, 0]) cylinder(h=8, d=4, center=true);
        }
    }
}

module end_effector(gripper_width=80, gripper_length=60, finger_length=40) {
    // Base
    color([0.3, 0.3, 0.3]) cube([gripper_width, gripper_length, 20], center=true);
    // Fingers
    color([0.5, 0.5, 0.5]) {
        translate([-gripper_width/4, gripper_length/2 + finger_length/2, 10]) cube([8, finger_length, 4], center=true);
        translate([gripper_width/4, gripper_length/2 + finger_length/2, 10]) cube([8, finger_length, 4], center=true);
    }
    // Actuator
    translate([0, -gripper_length/4, 15]) servo_motor(30, 25, 4, 10);
}

// Robotic Arm Assembly with Mechanical Components

// Base Assembly
translate([0, 0, 25.0]) {
    // Base plate
    color([0.7, 0.7, 0.7]) cylinder(h=50, d=200, center=true);
    // Mounting holes
    for (angle = [0:45:315]) {
        rotate([0, 0, angle]) translate([80.0, 0, 25.0]) cylinder(h=20, d=12, center=true);
    }
    // Shoulder joint mounting
    translate([0, 0, 35.0]) bearing(60, 30, 15);
}

// Shoulder Joint Assembly
translate([0, 0, 130.0]) {
    // Harmonic drive
    harmonic_drive(100, 90, 40);
    // Servo motor
    translate([0, 70.0, 0]) rotate([90, 0, 0]) servo_motor(60, 50, 8, 15);
    // Bearings
    translate([0, 0, 30]) bearing(90, 33, 10);
    translate([0, 0, -30]) bearing(90, 33, 10);
}

// Upper Arm Link
translate([140.0, 0, 210]) {
    robotic_link(280, 80, 4);
}

// Elbow Joint Assembly
translate([280, 0, 190]) {
    // Harmonic drive
    harmonic_drive(80, 72, 33);
    // Servo motor
    translate([0, 55.0, 0]) rotate([90, 0, 0]) servo_motor(50, 40, 6, 12);
    // Bearings
    translate([0, 0, 25]) bearing(72, 26, 8);
    translate([0, 0, -25]) bearing(72, 26, 8);
}

// Forearm Link
translate([440.0, 0, 190]) {
    robotic_link(320, 60, 3);
}

// Wrist Joint Assembly
translate([600, 0, 170]) {
    // Harmonic drive
    harmonic_drive(60, 54, 26);
    // Servo motor
    translate([0, 42.0, 0]) rotate([90, 0, 0]) servo_motor(40, 30, 5, 10);
    // Bearings
    translate([0, 0, 20]) bearing(54, 20, 6);
    translate([0, 0, -20]) bearing(54, 20, 6);
}

// End Effector
translate([650.0, 0, 170]) {
    end_effector(100, 100, 50);
}

// Coordinate system reference
translate([0, 0, 0]) {
    color([1, 0, 0, 0.5]) cylinder(h=50, d=2, center=true); // X-axis
    color([0, 1, 0, 0.5]) rotate([0, 90, 0]) cylinder(h=50, d=2, center=true); // Y-axis
    color([0, 0, 1, 0.5]) rotate([90, 0, 0]) cylinder(h=50, d=2, center=true); // Z-axis
}


if ($preview) {
    preview_axes(axis_len=1000.00);
    preview_origin_marker(size=6);
}
